# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: matcher.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rmatcher.proto\x12 sk.stuba.fei.api.msus.dp.matcher\"\xc0\x01\n\x18MatchFingerprintsRequest\x12R\n\x0esampleTemplate\x18\x01 \x01(\x0b\x32:.sk.stuba.fei.api.msus.dp.matcher.MatchFingerprintTemplate\x12P\n\x0crealTemplate\x18\x02 \x01(\x0b\x32:.sk.stuba.fei.api.msus.dp.matcher.MatchFingerprintTemplate\"#\n\rMatchResponse\x12\x12\n\nmatchScore\x18\x01 \x01(\x02\"L\n\x18MatchFingerprintTemplate\x12\x15\n\rkeypointsSize\x18\x01 \x01(\x05\x12\x19\n\x11\x65ncodedDescriptor\x18\x02 \x01(\t2\x8e\x01\n\x07Matcher\x12\x82\x01\n\x11MatchFingerprints\x12:.sk.stuba.fei.api.msus.dp.matcher.MatchFingerprintsRequest\x1a/.sk.stuba.fei.api.msus.dp.matcher.MatchResponse\"\x00\x42\x02P\x01\x62\x06proto3')



_MATCHFINGERPRINTSREQUEST = DESCRIPTOR.message_types_by_name['MatchFingerprintsRequest']
_MATCHRESPONSE = DESCRIPTOR.message_types_by_name['MatchResponse']
_MATCHFINGERPRINTTEMPLATE = DESCRIPTOR.message_types_by_name['MatchFingerprintTemplate']
MatchFingerprintsRequest = _reflection.GeneratedProtocolMessageType('MatchFingerprintsRequest', (_message.Message,), {
  'DESCRIPTOR' : _MATCHFINGERPRINTSREQUEST,
  '__module__' : 'matcher_pb2'
  # @@protoc_insertion_point(class_scope:sk.stuba.fei.api.msus.dp.matcher.MatchFingerprintsRequest)
  })
_sym_db.RegisterMessage(MatchFingerprintsRequest)

MatchResponse = _reflection.GeneratedProtocolMessageType('MatchResponse', (_message.Message,), {
  'DESCRIPTOR' : _MATCHRESPONSE,
  '__module__' : 'matcher_pb2'
  # @@protoc_insertion_point(class_scope:sk.stuba.fei.api.msus.dp.matcher.MatchResponse)
  })
_sym_db.RegisterMessage(MatchResponse)

MatchFingerprintTemplate = _reflection.GeneratedProtocolMessageType('MatchFingerprintTemplate', (_message.Message,), {
  'DESCRIPTOR' : _MATCHFINGERPRINTTEMPLATE,
  '__module__' : 'matcher_pb2'
  # @@protoc_insertion_point(class_scope:sk.stuba.fei.api.msus.dp.matcher.MatchFingerprintTemplate)
  })
_sym_db.RegisterMessage(MatchFingerprintTemplate)

_MATCHER = DESCRIPTOR.services_by_name['Matcher']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'P\001'
  _MATCHFINGERPRINTSREQUEST._serialized_start=52
  _MATCHFINGERPRINTSREQUEST._serialized_end=244
  _MATCHRESPONSE._serialized_start=246
  _MATCHRESPONSE._serialized_end=281
  _MATCHFINGERPRINTTEMPLATE._serialized_start=283
  _MATCHFINGERPRINTTEMPLATE._serialized_end=359
  _MATCHER._serialized_start=362
  _MATCHER._serialized_end=504
# @@protoc_insertion_point(module_scope)
