# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import matcher_pb2 as matcher__pb2


class MatcherStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.MatchFingerprints = channel.unary_unary(
                '/sk.stuba.fei.api.msus.dp.matcher.Matcher/MatchFingerprints',
                request_serializer=matcher__pb2.MatchFingerprintsRequest.SerializeToString,
                response_deserializer=matcher__pb2.MatchResponse.FromString,
                )


class MatcherServicer(object):
    """Missing associated documentation comment in .proto file."""

    def MatchFingerprints(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MatcherServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'MatchFingerprints': grpc.unary_unary_rpc_method_handler(
                    servicer.MatchFingerprints,
                    request_deserializer=matcher__pb2.MatchFingerprintsRequest.FromString,
                    response_serializer=matcher__pb2.MatchResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'sk.stuba.fei.api.msus.dp.matcher.Matcher', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Matcher(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def MatchFingerprints(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/sk.stuba.fei.api.msus.dp.matcher.Matcher/MatchFingerprints',
            matcher__pb2.MatchFingerprintsRequest.SerializeToString,
            matcher__pb2.MatchResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
