# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: feature-extractor.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17\x66\x65\x61ture-extractor.proto\x12)sk.stuba.fei.api.msus.dp.featureextractor\"(\n\x18\x46\x65\x61tureExtractionRequest\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\t\"Q\n\x1d\x46ingerprintExtractionResponse\x12\x15\n\rkeypointsSize\x18\x01 \x01(\x05\x12\x19\n\x11\x65ncodedDescriptor\x18\x02 \x01(\t2\xba\x01\n\x10\x46\x65\x61tureExtractor\x12\xa5\x01\n\x12\x45xtractFingerprint\x12\x43.sk.stuba.fei.api.msus.dp.featureextractor.FeatureExtractionRequest\x1aH.sk.stuba.fei.api.msus.dp.featureextractor.FingerprintExtractionResponse\"\x00\x42\x02P\x01\x62\x06proto3')



_FEATUREEXTRACTIONREQUEST = DESCRIPTOR.message_types_by_name['FeatureExtractionRequest']
_FINGERPRINTEXTRACTIONRESPONSE = DESCRIPTOR.message_types_by_name['FingerprintExtractionResponse']
FeatureExtractionRequest = _reflection.GeneratedProtocolMessageType('FeatureExtractionRequest', (_message.Message,), {
  'DESCRIPTOR' : _FEATUREEXTRACTIONREQUEST,
  '__module__' : 'feature_extractor_pb2'
  # @@protoc_insertion_point(class_scope:sk.stuba.fei.api.msus.dp.featureextractor.FeatureExtractionRequest)
  })
_sym_db.RegisterMessage(FeatureExtractionRequest)

FingerprintExtractionResponse = _reflection.GeneratedProtocolMessageType('FingerprintExtractionResponse', (_message.Message,), {
  'DESCRIPTOR' : _FINGERPRINTEXTRACTIONRESPONSE,
  '__module__' : 'feature_extractor_pb2'
  # @@protoc_insertion_point(class_scope:sk.stuba.fei.api.msus.dp.featureextractor.FingerprintExtractionResponse)
  })
_sym_db.RegisterMessage(FingerprintExtractionResponse)

_FEATUREEXTRACTOR = DESCRIPTOR.services_by_name['FeatureExtractor']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'P\001'
  _FEATUREEXTRACTIONREQUEST._serialized_start=70
  _FEATUREEXTRACTIONREQUEST._serialized_end=110
  _FINGERPRINTEXTRACTIONRESPONSE._serialized_start=112
  _FINGERPRINTEXTRACTIONRESPONSE._serialized_end=193
  _FEATUREEXTRACTOR._serialized_start=196
  _FEATUREEXTRACTOR._serialized_end=382
# @@protoc_insertion_point(module_scope)
