export enum FingerPosition {
  RIGHT_THUMB = 'RIGHT_THUMB',
  RIGHT_INDEX = 'RIGHT_INDEX',
  RIGHT_MIDDLE = 'RIGHT_MIDDLE',
  RIGHT_RING = 'RIGHT_RING',
  RIGHT_LITTLE = 'RIGHT_LITTLE',
  LEFT_THUMB = 'LEFT_THUMB',
  LEFT_INDEX = 'LEFT_INDEX',
  LEFT_MIDDLE = 'LEFT_MIDDLE',
  LEFT_RING = 'LEFT_RING',
  LEFT_LITTLE = 'LEFT_LITTLE',
}
